FROM mysql:5.7
WORKDIR /var/lib/mysql/

ENV MYSQL_ROOT_PASSWORD = Senha123

ENV MYSQL_DATABASE = meubanco

##essa linha indica que o conteiner subira ja com uma tabela criada
ADD sql.sql  /docker-entrypoint-initbd.d

EXPOSE 3306